### PR TITLE
chore: Added yup and react-hook-form libraries

### PR DESCRIPTION
**Pull request by Mykyta-Pysarev**

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
Could you also add some component with code example?

**Comment by Mykyta-Pysarev** [comment]
@alexandrtovmach You mean any forms with validation examples? Should it be related to some of the twitter forms?

**Comment by alexandrtovmach** [comment]
it's not important to be related to twitter, just add some code samples for the rest of the team to understand how to use this tools

**Comment by Mykyta-Pysarev** [comment]
@alexandrtovmach done

**Comment by Mykyta-Pysarev** [comment]
> it's not important to be related to twitter, just add some code samples for the rest of the team to understand how to use this tools

Done

**Review by alexandrtovmach — APPROVED** [review]

**Comment by VitaliiDenysiuk** [comment]
looks good for me

**Review by AndrewKaenko — APPROVED** [review]

**Review by VitaliiDenysiuk — APPROVED** [review]
ok

**Pull request merged**
