### PR TITLE
Feature/general wrapper style

### PR DESCRIPTION
**Pull request by Mykyta-Pysarev**
Change general wrapper styles.

**Now Navigation menu should be change to hide text if width is less than 1000px, or design will look hideous.**

More than 1280 px:
image
Less than 1280 px:
image
Less than 1000 px:
image
Less than 500 px:
image

### CODE REVIEW

**Comment by ArtemLigerko** [comment]
Looks good

**Review by ArtemLigerko — APPROVED** [review]

**Comment by DavidKorystov** [comment]
Shouldn't the navigation bar be less than 500px down, like in this photo.

image

**Comment by Mykyta-Pysarev** [comment]
Remade styles with bootstrap container and grid system.

**Comment by Mykyta-Pysarev** [comment]
> Shouldn't the navigation bar be less than 500px down, like in this photo.
> 
> image

Yes, it should. But I assume that first navigation bar should be updated with media query to work properly.

**Review by alexandrtovmach — APPROVED** [review]

**Pull request merged**
