### PR TITLE
created ReplyTweet component and added logic to comment button of FeedSingleTweet

### PR DESCRIPTION
**Pull request by Barylo**
Created new ReplyTweet component and added (inside FeedSingleTweet component) logic to comment button to open modal with this component on click .

### CODE REVIEW

**Comment by ArtemLigerko** [comment]
branch name is not comply to Git Branch Naming Convention (https://dev.to/couchcamote/git-branching-name-convention-cch)

**Comment by ArtemLigerko** [comment]
Is it possible to use (import) TweetCreationForm and add your ReplyTweet component as props, isntead copying hole code from it? 
Can you add screenshots how it looks now with your realization?

**Comment by Barylo** [comment]
> branch name is not comply to Git Branch Naming Convention (https://dev.to/couchcamote/git-branching-name-convention-cch)

Thanks, I agree with you. I promise that won't do such thing any more. Sorry

**Comment by Barylo** [comment]
> 

At first, I thought to do so, but then realized that TweetCreationForm is not reusable for now due to some differences like:
1) there should be another placeholder in the input field
2) TweetCreationForm do not allow children inside

So to go this way the first task is to rebuild TweetCreationForm to be reusable throught props and children. And then to make my task.

So I decided to go the simplest way for now, but may be it is worth to try to make your suggestions come true at the next substep. Let's discuss it online during today session

**Pull request closed without merging**
