### PR TITLE
fix: left navbar and language select layout

### PR DESCRIPTION
**Pull request by Mykyta-Pysarev**
Not perfect, but better:

image

### CODE REVIEW

**Review by VitaliiDenysiuk — CHANGES_REQUESTED** [review]
at my notebook I have problem.
I can not see button "Registration" and scroll absent
image

**Comment by Mykyta-Pysarev** [comment]
This buttons will be removed. Now menu sticked to the top and works on standard resolution.

**Review by KirillSerg — APPROVED** [review]
lgtm

**Review by valeriisuvyk — APPROVED** [review]
Looks good!

**Review by DavidKorystov — APPROVED** [review]

**Pull request merged**
